name: medica_consult
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #ICONS
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

  #State Management
  get: ^4.6.6
  get_storage: ^2.1.1
  provider: ^6.1.2

  #UTILITY PACKAGES
  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.0.1
  lottie: ^3.1.0
  url_launcher: ^6.1.12
  connectivity_plus: ^5.0.1
  flutter_native_splash: ^2.3.9
  smooth_page_indicator: ^1.1.0
  table_calendar: ^3.1.1
  custom_radio_grouped_button: ^2.2.1
  image_picker: ^1.0.7
  otp_text_field: ^1.1.3
  flutter_otp_text_field: ^1.1.3+2

  #REVIEW SPECIFIC
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
  record: ^4.4.4
  permission_handler: ^11.3.1
  path_provider: ^2.0.3
  voice_message_package: ^2.1.0
  camera: ^0.10.5+9
  path: ^1.8.3
  file_picker: ^8.0.0+1
  photo_view: ^0.14.0

  #GeoLocalization
  google_maps_flutter: ^2.2.8
  google_maps_flutter_android: ^2.7.0
  google_maps_flutter_platform_interface: ^2.6.0

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.14.2
  cloud_firestore: ^4.15.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/icons/categoryIcons/
    - assets/icons/payment_methods/
    - assets/icons/language/
    - assets/images/
    - assets/images/payment/
    - assets/images/on_boarding_images/
    - assets/images/doctors/
    - assets/images/document/
    - assets/images/animations/
    - assets/images/user/
    - assets/images/article/
    - assets/logos/

  uses-material-design: true



#-----LOCAL FONTS-----#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800