name: medica_consult
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #ICONS
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

  get: ^4.6.6
  get_storage: ^2.1.1

  #UTILITY PACKAGES
  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.0.1
  lottie: ^3.1.0
  url_launcher: ^6.1.12
  connectivity_plus: ^6.0.1
  flutter_native_splash: ^2.3.9
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/icons/categoryIcons/
    - assets/icons/payment_methods/
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/doctors/
    - assets/images/animations/
    - assets/images/user/
    - assets/images/article/
    - assets/logos/

  uses-material-design: true



